// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/new": {
    params: {};
  };
  "/items/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/new" | "/items/:id";
  };
  "routes/items.tsx": {
    id: "routes/items";
    page: "/";
  };
  "routes/newItem.tsx": {
    id: "routes/newItem";
    page: "/new";
  };
  "routes/item.tsx": {
    id: "routes/item";
    page: "/items/:id";
  };
};